name_network: "1st_koh"
network: "/home/miguel/6.Projects/BayesianFinalProject/sumo/networks/1st_koh.net.xml"
duration: 540 # 9 min
n_veh: 156
departure_time: 360 # 6 min

# OD: 1-8
routes:
  - ["E1_2_EB","E2_6_NB","E6_7_NEB","E7_8_NEB"]
  - ["E1_2_EB","E2_3_EB","E3_4_EB","E4_7_NWB","E7_8_NEB"]
  - ["E1_2_EB","E2_3_EB","E3_6_NWB","E6_7_NEB","E7_8_NEB"]

true_means_tt:
  - 58.72
  - 64.04
  - 79.97

true_std_tt:
  - 13.09
  - 6.78
  - 23.56

MoM_alpha:
  - 20.13
  - 89.21
  - 11.51